// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveBaseLeftFront = NULL;
SpeedController* RobotMap::driveBaseRightFront = NULL;
SpeedController* RobotMap::driveBaseLeftRear = NULL;
SpeedController* RobotMap::driveBaseRightRear = NULL;
RobotDrive* RobotMap::driveBaseRobotDrive = NULL;
SpeedController* RobotMap::liftMechanismLiftMotor = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveBaseLeftFront = new Talon(0);
	lw->AddActuator("DriveBase", "LeftFront", (Talon*) driveBaseLeftFront);
	
	driveBaseRightFront = new Talon(1);
	lw->AddActuator("DriveBase", "RightFront", (Talon*) driveBaseRightFront);
	
	driveBaseLeftRear = new Talon(2);
	lw->AddActuator("DriveBase", "LeftRear", (Talon*) driveBaseLeftRear);
	
	driveBaseRightRear = new Talon(3);
	lw->AddActuator("DriveBase", "RightRear", (Talon*) driveBaseRightRear);
	
	driveBaseRobotDrive = new RobotDrive(driveBaseLeftFront, driveBaseLeftRear,
              driveBaseRightFront, driveBaseRightRear);
	
	driveBaseRobotDrive->SetSafetyEnabled(true);
        driveBaseRobotDrive->SetExpiration(0.1);
        driveBaseRobotDrive->SetSensitivity(0.5);
        driveBaseRobotDrive->SetMaxOutput(1.0);

	liftMechanismLiftMotor = new Talon(4);
	lw->AddActuator("LiftMechanism", "LiftMotor", (Talon*) liftMechanismLiftMotor);
	

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
